In [ ]:
Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Ans-
     Yes, there is a difference in the data type of variables list_ and array_list.

The variable list_ is a Python list, whereas the variable array_list is a NumPy array.

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_ variable:", type(list_))
print("Data type of array_list variable:", type(array_list))


Output:
    
Data type of list_ variable: <class 'list'>
Data type of array_list variable: <class 'numpy.ndarray'>

Here, type(list_) returns <class 'list'>, indicating that the variable list_ is a Python list, and type(array_list) returns <class 'numpy.ndarray'>, indicating that the variable array_list is a NumPy array.

In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.
Ans-
    To print the data type of each and every element of both the variables list_ and array_list, you can use a for loop to iterate over each element and use the type() function to get the data type of each element as follows:
        
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of each element in list_ variable:")
for elem in list_:
    print(type(elem))

print("\nData type of each element in array_list variable:")
for elem in array_list:
    print(type(elem))
    
Output:
    
Data type of each element in list_ variable:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list variable:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>

Here, the for loop iterates over each element in the variable list_ and array_list, and the type() function is used to get the data type of each element. The output shows the data type of each element in both variables. In the case of the array_list variable, each element is of  numpy.str_ because the np.array() function converts the input list into a NumPy array of string data type.


In [ ]:
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Ans-
    Yes, there will be a difference in the data type of the elements present in both variables list_ and array_list after making the following change:
        
        array_list = np.array(object=list_, dtype=int)
        
Here, we are creating a NumPy array array_list from the list list_, and specifying the data type of the array as int. This means that the string elements in the original list will be converted to integer type.

To print the data type of each and every element present in both variables list_ and array_list, you can use a for loop to iterate over each element and use the type() function to get the data type of each element as follows:
    
    import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data type of each element in list_ variable:")
for elem in list_:
    print(type(elem))

print("\nData type of each element in array_list variable:")
for elem in array_list:
    print(type(elem))
    
     Output:
            
Data type of each element in list_ variable:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list variable:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
    
    Here, the for loop iterates over each element in the variable list_ and array_list, and the type() function is used to get the data type of each element. The output shows the data type of each element in both variables. In the case of the array_list variable, each element is of type numpy.int32 because we specified the data type of the array as int while creating it.  

In [ ]:
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

Ans-

To find the shape and size of the NumPy array num_array, you can use the shape and size attributes of the NumPy array as follows:
    
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)
     
Output:
    
Shape of num_array: (2, 3)
Size of num_array: 6  

Here, the shape attribute returns a tuple containing the dimensions of the array. In this case, num_array has 2 rows and 3 columns, so the shape is (2, 3).

The size attribute returns the total number of elements in the array. In this case, num_array has 6 elements, so the size is 6.
    

In [ ]:
Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

Ans-
   numpy.zeros function to create an array of zeros of a specific size and shape. Here's how you can create a 3x3 array of zeros using numpy:
    
import numpy as np

# create a 3x3 array of zeros
zeros_array = np.zeros((3, 3))

print(zeros_array)

Output:
    
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]    

The np.zeros function takes a tuple as its argument, where each element of the tuple represents the size of the corresponding dimension of the array. In this case, we want a 3x3 array, so we pass (3, 3) as the argument to np.zeros.

In [ ]:
Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

Ans-
   numpy.identity function to create an identity matrix of a specific shape. Here's how you can create a 5x5 identity matrix using numpy:
    
import numpy as np

# create a 5x5 identity matrix
identity_matrix = np.identity(5)

print(identity_matrix)

Output:
    
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
    
    
The np.identity function takes a single argument, which specifies the size of the identity matrix to create. In this case, we want a 5x5 identity matrix, so we pass 5 as the argument to np.identity. The resulting matrix will have 1s on the main diagonal (from top-left to bottom-right) and 0s everywhere else.