## Part 1: Theoretical Queltions.

### Q1. What are the different data structures used in Tensorflow? Give some examples.

TensorFlow, an open-source machine learning framework, primarily uses tensors as the fundamental data structure for representing and manipulating data. However, TensorFlow also provides several specialized data structures and containers that are commonly used in conjunction with tensors. Here are some of the key data structures used in TensorFlow:

1. **Tensor:** A tensor is a multi-dimensional array, similar to a matrix or a NumPy array. Tensors are the primary data structure used for computations in TensorFlow. Tensors can have different ranks (number of dimensions) such as scalars (rank-0), vectors (rank-1), matrices (rank-2), and higher-dimensional tensors. Examples include:

   - Scalar: 5
   - Vector: [1, 2, 3]
   - Matrix: [[1, 2], [3, 4]]

2. **Variable:** A Variable is a special type of tensor that allows for mutable state. It is often used to represent trainable parameters in machine learning models. Variables can be updated during the training process, making them suitable for storing and updating model weights and biases.

3. **Placeholder:** In earlier versions of TensorFlow, placeholders were used to define inputs to a computational graph. However, as of TensorFlow 2.0, eager execution is the default mode, and placeholders are no longer necessary. Placeholder-like behavior can be achieved using regular tensors or function arguments.

4. **SparseTensor:** A SparseTensor is a data structure used to efficiently represent tensors with a large number of zero or sparse values. It stores only the non-zero values and their corresponding indices, reducing memory consumption and improving computation speed for sparse data.

5. **Dataset:** The Dataset API provides a way to represent a collection of data elements, such as training or validation samples, as a sequence of elements. Datasets are designed to efficiently handle large volumes of data and provide various operations for data preprocessing and transformation, such as shuffling, batching, and mapping.

6. **RaggedTensor:** A RaggedTensor is used to represent tensors with varying dimensions along one or more axes. It is suitable for irregular or nested data structures where the number of elements in a tensor's dimensions can vary. Examples include sentences of varying lengths or hierarchical data.

7. **SparseTensorValue:** This is not a data structure per se, but it represents the value of a SparseTensor in TensorFlow. It contains the non-zero values and their corresponding indices in a sparse tensor.

### Q2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.

In TensorFlow, constants and variables are two different types of data structures that serve distinct purposes in building and training machine learning models. Here's how they differ:

**TensorFlow Constant:**
- A constant in TensorFlow is a fixed value that remains unchanged throughout the execution of a computational graph.
- Once a constant is defined, its value cannot be modified.
- Constants are typically used to represent fixed values such as hyperparameters or input data that doesn't require updates during training.
- Constants are primarily used for providing inputs to the model.
- The value of a constant is set during its initialization and remains the same during the entire execution.

In [1]:
import tensorflow as tf

# Creating a TensorFlow constant
constant = tf.constant(5)
constant.numpy()

2023-07-25 03:39:24.935420: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-07-25 03:39:25.008154: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-07-25 03:39:25.009644: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-25 03:39:26.223057: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


5

**TensorFlow Variable:**

- A variable in TensorFlow represents a mutable state that can be updated and modified during model training.
- Variables are typically used to store and update trainable parameters such as weights and biases in machine learning models.
- Unlike constants, variables can be modified by TensorFlow operations during training.
- Variables are initialized with an initial value, but their values can change as the model learns and updates its parameters.

In [2]:
import tensorflow as tf

variable = tf.Variable(initial_value=tf.random.normal(shape=(3, 3)), trainable=True)
variable

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 1.6473486 ,  1.2147368 , -0.05718518],
       [-1.2673038 ,  2.0999029 , -0.7397722 ],
       [ 0.00845411,  0.20931548,  0.06121462]], dtype=float32)>

### Q3. Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.

**Matrix addition**

In [3]:
mat1=tf.constant([[1,2],[3,4]])
mat2=tf.constant([[5,6],[7,8]])

res=tf.add(mat1, mat2) 
res

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]], dtype=int32)>

**Matrix multilpication**

In [5]:
mat1=tf.constant([[1,2],[3,4]])
mat2=tf.constant([[5,6],[7,8]])

res=tf.matmul(mat1,mat2)
res

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>

**Element-wise Operation:**

In [6]:
tensor1 = tf.constant([1, 2, 3])
tensor2 = tf.constant([4, 5, 6])

add_res=tf.add(tensor1,tensor2)
mul_res=tf.multiply(tensor1,tensor2)

print(add_res)
print()
print(mul_res)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


## Part2 : Practical Implementation

### Task 1: Creating and Manipulating Matrices

### Q1. Create a normal matrix A with dimensions 3x3, using TensorFlow's random_normal function. Display the values of matrix A.

In [7]:
matrixA=tf.random.normal(shape=(3,3))
print(matrixA)

tf.Tensor(
[[-1.1735085   1.7233868   1.4016247 ]
 [-1.2425873  -0.4366313   1.0251307 ]
 [-0.23029867  1.4646338   0.80734426]], shape=(3, 3), dtype=float32)


### Q2. Create a Gaussian matrix B with dimensions 4x4, using TensorFlow's truncated_normal function. Display the values of matrix B.

In [8]:
matrixB=tf.random.truncated_normal(shape=(4,4))
matrixB

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-0.5403124 , -1.2507607 ,  0.94073445,  1.0686661 ],
       [-0.30233297, -0.3267241 , -0.1009445 ,  0.1842022 ],
       [ 0.22749132,  0.06035215, -1.294187  ,  1.1331745 ],
       [ 0.44121972, -0.3131718 , -1.891981  , -1.7183754 ]],
      dtype=float32)>

### Q3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 3 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix.

In [9]:
matrixC=tf.random.normal(shape=(2,2),mean=3,stddev=0.5)
matrixC

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3.6916642, 2.635573 ],
       [2.4696822, 3.9134262]], dtype=float32)>

### Q4.Perform matrix addition between matrix A and matrix B, and store the result in matrix D

matrixD=matrixA+matrixB

#### >>>Matrix_A and Matrix_B are of different dimension hence Cannot be Added

### Q5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

#### >>>Since Matrix_C is not possible ,hence Matrix_E is also not possible

### Task 2: Performing Additional Matrix Operation.

### Q1. Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform function.

In [11]:
matrixF=tf.random.uniform(shape=(2,2))
print(matrixF)

tf.Tensor(
[[0.41192222 0.6066272 ]
 [0.18577075 0.37560213]], shape=(2, 2), dtype=float32)


### Q2.  Calculate the transpose of matrix F and store the result in matrix G.

In [13]:
matrixG=tf.transpose(matrixF)
matrixG

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.41192222, 0.18577075],
       [0.6066272 , 0.37560213]], dtype=float32)>

### Q3.Calculate the element-wise exponential of matrix F and store the result in matrix H.

In [14]:
matrixH=tf.exp(matrixF)
matrixH

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.509717 , 1.8342345],
       [1.2041461, 1.4558678]], dtype=float32)>

### Q4. Create a matrix I by concatenating matrix F and matrix G horizontally.

In [15]:
matrixI=tf.concat((matrixF,matrixG), axis=1)
print("Matrix I (concatenation of F and G horizontally):")
print(matrixI)

Matrix I (concatenation of F and G horizontally):
tf.Tensor(
[[0.41192222 0.6066272  0.41192222 0.18577075]
 [0.18577075 0.37560213 0.6066272  0.37560213]], shape=(2, 4), dtype=float32)


### Q5. Create a matrix J by concatenating matrix F and matrix H vertically.

In [16]:
matrixJ=tf.concat((matrixF,matrixG), axis=0)
print("Matrix J (concatenation of F and H vertically):")
print(matrixJ)

Matrix J (concatenation of F and H vertically):
tf.Tensor(
[[0.41192222 0.6066272 ]
 [0.18577075 0.37560213]
 [0.41192222 0.18577075]
 [0.6066272  0.37560213]], shape=(4, 2), dtype=float32)
